### ISSUE TITLE
please give me some tips on using it 

### ISSUE THREAD

**Issue by helxsz** [tchayen/red-otter#3]
Hi, @tchayen It looks very powerful to render the ui in webgl, my first idea of its usage is to use it to render the UI mock, like framer.com(it seems to be rending on html), if using red-otter, it takes an extra step to convert to canvas to html. 

So i am still not very clear where can i go further in working on the library, please give me some tips given my knowledge is too few.

**Comment by tchayen** [comment]
Hi!

I never used framer.com so I don't know how they do rendering, but using `red-otter` for some UI editor is definitely a nice idea. Figma has its own WebGL based editor since forever and it's a great piece of software.

Another use case is if you are doing some financial software and you have to display a spreadsheet with thousands of columns that need to stay fast and smooth. I have seen people implement their own custom renderers based on browser Canvas API to fight with that, so in that kind of case `red-otter` is a lightweight (just ~15kB added to your JS bundle) solution that makes working with any kind of UI way way easier. I haven't done any benchmarks yet at this stage so I cannot link to any data supporting this case, but I will definitely explore this in the future.

And finally a very big use case is usage in 3D scenes and games and this is where `red-otter` will shine. Although it is possible to tie WebGL to HTML when using `react-three-fiber` (example: [link](https://codesandbox.io/s/github/onion2k/r3f-by-example/tree/develop/examples/other/html-labels)) this probably doesn't scale well for much more complex UIs. Also it assumes that you have access to HTML DOM and that you are fine with leaving to browser how exactly the UI will look, how fonts will be rasterized etc.

By doing all the groundwork and reinventing everything from scratch, `red-otter` scales great way past web browsers. It's a bunch of simple APIs that render layout and need some renderer to draw on screen. Fun fact: first implementation of `red-otter` was written in Zig and I was running it both as a native macOS app and in browser through WASM and OpenGL <-> WebGL bindings. But again, because this is simple, no-dependency code, I was able to quickly rewrite it to TypeScript to avoid friction with complicated setup.
